/**
 * Correios API
 * API para acessar web services dos correios
 *
 * OpenAPI spec version: 0.0.1
 * Contact: amadeu01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CorreiosApi);
  }
}(this, function(expect, CorreiosApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CorreiosApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('calcPrazoDataGet', function() {
      it('should call calcPrazoDataGet successfully', function(done) {
        //uncomment below and update the code to test calcPrazoDataGet
        //instance.calcPrazoDataGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrazoDataPost', function() {
      it('should call calcPrazoDataPost successfully', function(done) {
        //uncomment below and update the code to test calcPrazoDataPost
        //instance.calcPrazoDataPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrazoGet', function() {
      it('should call calcPrazoGet successfully', function(done) {
        //uncomment below and update the code to test calcPrazoGet
        //instance.calcPrazoGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrazoPost', function() {
      it('should call calcPrazoPost successfully', function(done) {
        //uncomment below and update the code to test calcPrazoPost
        //instance.calcPrazoPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrazoRestricaoGet', function() {
      it('should call calcPrazoRestricaoGet successfully', function(done) {
        //uncomment below and update the code to test calcPrazoRestricaoGet
        //instance.calcPrazoRestricaoGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrazoRestricaoPost', function() {
      it('should call calcPrazoRestricaoPost successfully', function(done) {
        //uncomment below and update the code to test calcPrazoRestricaoPost
        //instance.calcPrazoRestricaoPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoDataGet', function() {
      it('should call calcPrecoDataGet successfully', function(done) {
        //uncomment below and update the code to test calcPrecoDataGet
        //instance.calcPrecoDataGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoDataPost', function() {
      it('should call calcPrecoDataPost successfully', function(done) {
        //uncomment below and update the code to test calcPrecoDataPost
        //instance.calcPrecoDataPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoFACGet', function() {
      it('should call calcPrecoFACGet successfully', function(done) {
        //uncomment below and update the code to test calcPrecoFACGet
        //instance.calcPrecoFACGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoFACPost', function() {
      it('should call calcPrecoFACPost successfully', function(done) {
        //uncomment below and update the code to test calcPrecoFACPost
        //instance.calcPrecoFACPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoGet', function() {
      it('should call calcPrecoGet successfully', function(done) {
        //uncomment below and update the code to test calcPrecoGet
        //instance.calcPrecoGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoPost', function() {
      it('should call calcPrecoPost successfully', function(done) {
        //uncomment below and update the code to test calcPrecoPost
        //instance.calcPrecoPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoPrazoDataGet', function() {
      it('should call calcPrecoPrazoDataGet successfully', function(done) {
        //uncomment below and update the code to test calcPrecoPrazoDataGet
        //instance.calcPrecoPrazoDataGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoPrazoDataPost', function() {
      it('should call calcPrecoPrazoDataPost successfully', function(done) {
        //uncomment below and update the code to test calcPrecoPrazoDataPost
        //instance.calcPrecoPrazoDataPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoPrazoRestricaoGet', function() {
      it('should call calcPrecoPrazoRestricaoGet successfully', function(done) {
        //uncomment below and update the code to test calcPrecoPrazoRestricaoGet
        //instance.calcPrecoPrazoRestricaoGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('calcPrecoPrazoRestricaoPost', function() {
      it('should call calcPrecoPrazoRestricaoPost successfully', function(done) {
        //uncomment below and update the code to test calcPrecoPrazoRestricaoPost
        //instance.calcPrecoPrazoRestricaoPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
